-- 1. Create profiles table
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- 2. Create diary_entries table
create table diary_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content jsonb not null, -- Stores repentance, resolve, dream as JSON
  is_public boolean default false
);

-- 3. Set up Row Level Security (RLS)
-- Enable RLS
alter table profiles enable row level security;
alter table diary_entries enable row level security;

-- Profiles policies
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Diary policies
create policy "Users can view their own diary entries."
  on diary_entries for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own diary entries."
  on diary_entries for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own diary entries."
  on diary_entries for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own diary entries."
  on diary_entries for delete
  using ( auth.uid() = user_id );

-- 4. Create a trigger to automatically create a profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
